apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ton-cat-lottery
  labels:
    app: backend
    project: ton-cat-lottery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        project: ton-cat-lottery
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: backend
        image: asia-east1-docker.pkg.dev/ton-cat-lottery-dev-2/ton-cat-lottery/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: TON_NETWORK
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ton_network
        - name: LOTTERY_CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: lottery_contract_address
        - name: NFT_CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: nft_contract_address
        - name: AUTO_DRAW
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: auto_draw
        - name: WALLET_PRIVATE_KEY
          value: "demo-key-for-testing"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Temporarily disabled health checks due to wallet configuration issues
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: http
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: http
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL