apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ton-cat-lottery
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http