apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ton-cat-lottery
  labels:
    app: backend
    project: ton-cat-lottery
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backend