apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ton-cat-lottery
  labels:
    app: frontend
    version: v1
    component: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
        component: web
      annotations:
        prometheus.io/scrape: "false"
    spec:
      # 註：nginx 需要 root 權限來綁定端口和寫入系統目錄
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      containers:
      - name: frontend
        image: asia-east1-docker.pkg.dev/ton-cat-lottery-dev-468008/ton-cat-lottery/frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_API_URL
        - name: VITE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_ENVIRONMENT
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "256Mi"
          limits:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "512Mi"
        # 註：暫時移除 securityContext 以避免 nginx 權限問題
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   readOnlyRootFilesystem: false
        #   capabilities:
        #     drop:
        #     - ALL
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      terminationGracePeriodSeconds: 30
      restartPolicy: Always