apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ton-cat-lottery
  labels:
    app: frontend
    project: ton-cat-lottery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        project: ton-cat-lottery
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: asia-east1-docker.pkg.dev/ton-cat-lottery-dev-2/ton-cat-lottery/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: nginx-pid
          mountPath: /var/run
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-pid
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}