apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ton-cat-lottery
  labels:
    app: frontend
    project: ton-cat-lottery
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend