apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ton-cat-lottery
  labels:
    app: frontend
    component: web
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http