apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ton-cat-lottery
  labels:
    app: frontend
    component: config
data:
  VITE_API_URL: "http://backend-service:8080"
  VITE_ENVIRONMENT: "production"