apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/ton-cat-lottery-dev/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "info"
        - name: TON_API_ENDPOINT
          value: "https://testnet.toncenter.com/api/v2/"
        - name: TON_NETWORK
          value: "testnet"
        - name: LOTTERY_CONTRACT_ADDRESS
          value: "EQD4FPq-PRDieyQKkizFTRtSDyucUIqrj0v_zXJmqaDp6_0t"  # 測試用地址
        - name: NFT_CONTRACT_ADDRESS
          value: "EQD4FPq-PRDieyQKkizFTRtSDyucUIqrj0v_zXJmqaDp6_0t"  # 測試用地址
        - name: WALLET_PRIVATE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000000"  # 測試用私鑰
        - name: DRAW_INTERVAL
          value: "5m"
        - name: MAX_PARTICIPANTS
          value: "3"
        - name: MIN_PARTICIPANTS
          value: "1"
        - name: ENTRY_FEE_TON
          value: "0.01"
        - name: AUTO_DRAW
          value: "false"
        - name: RETRY_COUNT
          value: "3"
        - name: RETRY_DELAY
          value: "5s"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # 後端是守護進程，不提供 HTTP API，暫時移除健康檢查
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP 