name: Simple CI

on:
  push:
    branches: [ main, master, feature/devops ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Code Quality & Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    # Test smart contracts
    - name: Test contracts
      run: |
        cd contracts
        npm ci
        npm run test

    # Test frontend
    - name: Build frontend
      run: |
        cd frontend
        npm ci
        npm run build

    # Test backend
    - name: Test backend
      run: |
        cd backend
        chmod +x test.sh
        ./test.sh

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build backend image
    - name: Build backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.backend
        platforms: linux/amd64
        push: false
        tags: backend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Build frontend image
    - name: Build frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.frontend
        platforms: linux/amd64
        push: false
        tags: frontend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Success
      run: echo "✅ All tests and builds completed successfully!"