name: CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache contracts node modules
      uses: actions/cache@v3
      with:
        path: contracts/node_modules
        key: ${{ runner.os }}-contracts-${{ hashFiles('contracts/package-lock.json') }}

    - name: Cache frontend node modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}

    - name: Install contract dependencies
      run: |
        cd contracts
        npm ci

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Build smart contracts
      run: |
        cd contracts
        npm run build

    - name: Test smart contracts
      run: |
        cd contracts
        npm run test

    - name: Test frontend build
      run: |
        cd frontend
        npm run build

    - name: Test Go backend
      run: |
        cd backend
        chmod +x test.sh
        ./test.sh

  docker-build:
    name: Docker Build Verification
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.backend
        push: false
        tags: ton-cat-lottery-backend:ci

    - name: Build frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.frontend
        push: false
        tags: ton-cat-lottery-frontend:ci

    - name: Verify Docker images
      run: |
        docker images | grep ton-cat-lottery